import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

/**
 * Clerk runs on every request, reads the session, and guards the private
 * routes.
 *
 * This is `middleware.ts`, not Next 16's newer `proxy.ts`, on purpose:
 * proxy.ts is locked to the Node.js runtime, and Cloudflare Workers only
 * runs Next.js middleware on the Edge runtime. middleware.ts is deprecated
 * in Next 16 but still supported, and is the only form that deploys to
 * Workers today. Revisit when OpenNext supports Node middleware.
 *
 * /pricing stays public: prospective customers — and payment providers
 * reviewing the site — must be able to see what is sold and for how much
 * without creating an account.
 */
const isProtectedRoute = createRouteMatcher([
  "/dashboard(.*)",
  "/vehicles(.*)",
  "/copilot(.*)",
  "/security(.*)",
]);

/**
 * Content-Security-Policy.
 *
 * Generated by Clerk rather than hand-written, because the allowlist it needs
 * is long, undocumented in places, and changes — it includes Clerk's abuse
 * and fraud protection hosts automatically on @clerk/nextjs >= 7.5.21. A
 * hand-maintained list would drift and break sign-in the day Clerk adds a
 * host.
 *
 * Default mode, not `strict: true`. Strict mode issues a per-request nonce
 * that every inline script must then carry, which is a larger change to make
 * against a live product on Workers — and a CSP that breaks sign-in or
 * checkout is worse than one that is merely good. The honest trade: default
 * mode keeps 'unsafe-inline' in script-src, so this does NOT stop an inline
 * XSS payload. What it does stop is the step that makes XSS profitable —
 * loading code from, or exfiltrating data to, a host that is not on this
 * list. Revisit strict mode once checkout and sign-in are covered by tests.
 */
const cspDirectives = {
  // Whop's checkout embed: loader plus the per-plan script it fetches.
  // Verified against a live 404 earlier — t.whop.tw serves /e/<planId>.js.
  "script-src": ["https://js.whop.com", "https://t.whop.tw"],
  // The payment form itself renders in a whop.com iframe.
  "frame-src": ["https://*.whop.com"],
  "connect-src": [
    "https://*.whop.com",
    // Supabase. The browser queries it directly through supabase-js on every
    // signed-in page, so omitting it does not weaken the policy — it breaks
    // the product. Read from the same variable the client is built with, so
    // pointing at a different project cannot leave this behind.
    process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  ].filter(Boolean),
};

export default clerkMiddleware(
  async (auth, request) => {
    if (!isProtectedRoute(request)) return;

    const { userId } = await auth();
    if (!userId) {
      // Deliberately not auth.protect(): in Next 16's proxy it redirects to the
      // current URL instead of the sign-in page, which silently defeats the
      // guard. Building the redirect by hand avoids that.
      const url = new URL("/login", request.url);
      url.searchParams.set("redirect_url", request.nextUrl.pathname);
      return NextResponse.redirect(url);
    }
  },
  { contentSecurityPolicy: { directives: cspDirectives } }
);

export const config = {
  matcher: [
    // Everything except Next internals and static assets…
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    // …plus API routes, so handlers always see the session…
    "/(api|trpc)(.*)",
    // …plus Clerk's own frontend API paths.
    "/__clerk/(.*)",
  ],
};
